"""empty message

Revision ID: c4e0fa94e005
Revises: 
Create Date: 2023-02-05 17:49:21.186509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e0fa94e005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('permission', sa.Enum('MODERATE', 'ADMIN', 'USER', name='permissions'), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
